version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    build: db/
    environment:
      POSTGRES_DB: calorie
      POSTGRES_USER: azizbek
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./db/data:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_HOST: postgres
      DB_USER: azizbek
      DB_NAME: calorie
      DB_PASSWORD: 12345
      DB_PORT: 5432
    depends_on:
      - postgres
  client:
    container_name: client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
