version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    build: db/
    environment:
      POSTGRES_DB: calorie
      POSTGRES_USER: azizbek
      POSTGRES_PASSWORD: 12345
      TZ: Asia/Tashkent
    ports:
      - 5433:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_HOST: postgres
      DB_USER: azizbek
      DB_NAME: calorie
      DB_PASSWORD: 12345
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - 3000:3000
  # client:
  #   container_name: client
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
